# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Python CDK Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: install web app dependencies
      working-directory: ./web
    
    - name: build web app
      working-directory: ./web
      run: npm run build
    
    - name: install AWS CDK
      run: sudo npm i -g aws-cdk

    - name: install AWS CDK
      working-directory: ./py-webdepl
      run: pip3 install -r requirements.txt
    
    -name: cdk synth
      working-directory: ./py-webdepl
      run: cdk synth

    -name: cdk deploy
      working-directory: ./py-webdepl
      env: 
        AWS_ACCESS_KEY_ID: $${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: $${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: $${{ secrets.AWS_REGION}}
      run: cdk deploy